; *******************************************************************
;    ThinkPad Maintenance Utilities Configuration File 
;    - tpconfig.ini
;    Version 1.01
;    Copyright Lenovo 2020 All Rights Reserved
; ********************************************************************

[advanced features]
hide_adv =  0 ; Advanced Menu
; hide_adv=1 ; Traditional Menu

