;This file is EEPROM configuration file
;Digital only accept decimal and hexadecimal
;Section "EEPROM STRUCTURE" is used to set the structure size and the software SMI.
;Size              default : 4096 (Bytes)
;SwSmi             default : 0
[EEPROM STRUCTURE]
Size=4096
SwSmi=0xC0

;Other Section is used to set the tool commands.
;Every Section only can set one rcommand(Read), and wcommand(Write).
;Type byte, word, dword, qword support multiparameter.
;Offset     : The EEPROM data offset.
;length     : The size of the data.
;rcommand   : The command set for read data.
;wcommand   : The command set for write data.
;type       : The type of the command. (Only accept byte, word, dword, qword, astring, ustring, GUID)
; - byte    : The command data is a byte array.
; - word    : The command data is a word array.
; - dword   : The command data is a dword array.
; - qword   : The command data is a qword array.
; - astring : The command data is a character array string.
; - ustring : The command data is a wide character array string.
; - GUID    : The command data is a Globally Unique Identifier. format: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
;For Example:
;1. Set four command to initial the tools
;
[Product Name]
Offset = 0x00
length = 0x41
rcommand = /rpn
wcommand = /wpn
type=astring
;
[Serial Number]
Offset=0x60
length=0x21
rcommand=/rsn
wcommand=/wsn
type=astring
;
[UUID]
Offset=0x90
length=0x10
rcommand=/ruu
wcommand=/wuu
type=guid
;
[ProjectName]
Offset=0xA0
length=0x41
rcommand=/rpr
wcommand=/wpr
type=astring
;
[KBID]
Offset=0xF0
length=0x01
rcommand=/rkb
wcommand=/wkb
type=byte
;
[BTID]
Offset=0xF1
length=0x01
rcommand=/rbt
wcommand=/wbt
type=byte
;
[EPAF]
Offset=0xF2
length=0x01
rcommand=/rel
wcommand=/wel
type=byte
;
[FunctionFlag]
Offset=0xF3
length=0x01
rcommand=/rfl
wcommand=/wfl
type=byte
;
[Customer]
Offset=0xF4
length=0x01
rcommand=/rcs
wcommand=/wcs
type=byte
;
[Family]
Offset=0x100
length=0x41
rcommand=/rf
wcommand=/wf
type=astring
;
[AssetFlag]
Offset=0x150
length=0x11
rcommand=/rAss
wcommand=/wAss
type=astring
;
[OSPN]
Offset=0x170
length=0x11
rcommand=/rospn
wcommand=/wospn
type=astring
;
[OSDES]
Offset=0x190
length=0x21
rcommand=/rOSD
wcommand=/wOSD
type=astring
;
[MTM]
Offset=0x1C0
length=0x41
rcommand=/rmtm
wcommand=/wmtm
type=astring
;
[OA3KEYID]
Offset=0x210
length=0x21
rcommand=/roa
wcommand=/woa
type=astring
;
[BOOTS]
Offset=0x50
length=0x01
rcommand=/rBS
wcommand=/wBS
type=byte
;
[SecureBoot]
Offset=0x51
length=0x01
rcommand=/rSB
wcommand=/wSB
type=byte
;
[FreeDOS]
Offset=0x52
length=0x01
rcommand=/rfo
wcommand=/wfo
type=byte
;
[XiaoXin]
Offset=0x53
length=0x01
rcommand=/rxo
wcommand=/wxo
type=byte
;
[OA21]
Offset=0x54
length=0x01
rcommand=/roa2
wcommand=/woa2
type=byte
;
;2. Write Command :
;EEPROM.exe /wpn "Name ABCDE" /wsn 12345678-9999-0000 /wuu "00112233-4455-6677-8899-AABBCCDDEEFF" /wv 0x0199ABCDEF 18765284782899
;
;0000   4E 00 61 00 6D 00 65 00 20 00 41 00 42 00 43 00    N.a.m.e. .A.B.C.
;0010   44 00 45 00 00 00 00 00 00 00 00 00 00 00 00 00    D.E.............
;0020   31 32 33 34 35 36 37 38 2D 39 39 39 39 2D 30 30    12345678-9999-00
;0030   30 30 00 00 00 00 00 00 00 00 00 00 00 00 00 00    00..............
;0040   33 22 11 00 55 44 77 66 88 99 AA BB CC DD EE FF    3"..udWF??????? 
;0050   EF CD AB 99 01 00 00 00 33 33 22 22 11 11 00 00    ????....33""....
;0060   ...
;0070   ...
;
;3. Read Command :
;EEPROM.exe /rpn /rsn /ruu /rv
;
;[Product Name] : Name ABCDE
;[Serial Number] : 12345678-9999-0000
;[UUID] : 00112233-4455-6677-8899-AABBCCDDEEFF
;[Value] : 0x0000000199ABCDEF 0x0000111122223333
